# Generated by Django 5.0.6 on 2024-06-23 21:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
