# Generated by Django 5.0.6 on 2024-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
