# Generated by Django 5.0.6 on 2024-06-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0011_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
