# Generated by Django 5.0.6 on 2024-06-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0013_coment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
